import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Link from "next/link";
import Cases from "@/components/Cases";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <div className="font-bold">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-[50vh]">
                <Header />

                <section className="bg-white w-[90%] mx-auto 2xl:w-[1280px]">
                    <h2 className="text-white mix-blend-difference text-[30px] lg:text-[50px]">
                        <div>Creating unique brands is</div>
                        <div>what we do.</div>
                    </h2>

                    <div className="flex items-center gap-x-4 text-2xl font-semibold pt-6 lg:text-3xl">
                        More about us{" "}
                        <Link
                            href={""}
                            className="flex items-center justify-center rounded-full border-[2px] border-black h-12 w-12 hover:bg-black hover:text-white transition duration-500"
                        >
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                                strokeWidth={1.5}
                                stroke="currentColor"
                                className="w-6 h-6 inline"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
                                />
                            </svg>
                        </Link>
                    </div>
                </section>
            </div>

            <div className="h-[50vh] flex  flex-col md:flex-row">
                <Cases />
            </div>
        </div>
    );
}
